###consul服务端端口
server:
  port: 8001

spring:
  application:
    name: cloud-provider-goods
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


